[functions.macswap]
path = "../functions/macswap"

[functions.decrement-ip-ttl]
path = "../functions/decrement-ip-ttl"

[[links]]
from = "rx"
to = ["macswap"]

[[links]]
from = "macswap"
to = ["decrement-ip-ttl"]

[[links]]
from = "decrement-ip-ttl"
to = ["tx"]
