[functions.load-balance]
path = "../functions/load-balance"
maps = { upcall_likelihood = { type = "array", size = 1 } }

[functions.macswap]
path = "../functions/macswap"

[functions.compute-heavy-xdp]
path = "../functions/compute-heavy-xdp"

[[links]]
from = "rx"
to = ["load-balance"]

[[links]]
from = "load-balance"
to = ["macswap", "compute-heavy-xdp"]

[[links]]
from = "compute-heavy-xdp"
to = ["macswap"]

[[links]]
from = "macswap"
to = ["tx"]
