[package]
name = "load-balance"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
xdp = ["nf/xdp"]
user = ["nf/user"]

[dependencies]
nf = { path = "../../../nf" }

[workspace]
